### ISSUE TITLE
Crashes following recent Replugged updates

### ISSUE THREAD

**Issue by ghost** [SammCheese/AFK-on-exit#3]
My apologies if you're no longer updating this following the move to replugged :)

One of the more recent updates to Replugged has introduced a crash when this addon tries to switch the status to idle. Unfortunately I can't narrow it down to which update as I didn't realize it was this plugin until today. If I had to guess it would have been sometime after replugged-org/replugged@9cc331cef109b827f634ac4191d6b4282628b716.

**Comment by SammCheese** [comment]
Looks like discord removed the function that was used to change the status. ill try to find an alternative

**Comment by SammCheese** [comment]
Is fix
